MyWebShop/Models/Cartridges/AddCartridgeFormModel.cs
namespace MyWebShop.Models.Cartridges
{
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using static Data.DataConstants;
    public class AddCartridgeFormModel
    {
        [Required]
        [StringLength(CartridgeModelMaxLength,MinimumLength=CartridgeModelMinLength)]
        public string Model { get; init; }

        [Required]
        [StringLength(
            int.MaxValue,
            MinimumLength = CartridgeDescriptionMinLength,
            ErrorMessage = "The field Description must be a string with a minimum length of {2}.")]
        public string Description { get; init; }

        [Display(Name = "Image URL")]
        [Required]
        [Url]
        public string ImageUrl { get; init; }
       
        public decimal? Price { get; set; }

        [Display(Name = "Colour")]
        public int ColourId { get; init; }

        public IEnumerable<CartridgeColourViewModel> Colours { get; set; }
        [Display(Name ="Printer")]
        public int PrinterId { get; init; }
        public IEnumerable<CartridgePrinterViewModel> Printers { get; set; }
    }
}

MyWebShop/Models/Cartridges/CartridgeFormModel.cs
namespace MyWebShop.Models.Cartridges
{
    using MyWebShop.Services.Cartridges;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using static Data.DataConstants;
    public class CartridgeFormModel
    {
        [Required]
        [StringLength(CartridgeModelMaxLength,MinimumLength=CartridgeModelMinLength)]
        public string Model { get; init; }

        [Required]
        [StringLength(
            int.MaxValue,
            MinimumLength = CartridgeDescriptionMinLength,
            ErrorMessage = "The field Description must be a string with a minimum length of {2}.")]
        public string Description { get; init; }

        [Display(Name = "Image URL")]
        [Required]
        [Url]
        public string ImageUrl { get; init; }
       
        public decimal Price { get; set; }

        [Display(Name = "Colour")]
        public int ColourId { get; init; }

        public IEnumerable<CartridgeColourServiceModel> Colours { get; set; }
        [Display(Name ="Printer")]
        public int PrinterId { get; init; }
        public IEnumerable<CartridgePrinterServiceModel> Printers { get; set; }
    }
}

MyWebShop/Models/Cartridges/CartridgesSearchQueryModel.cs
namespace MyWebShop.Models.Cartridges
{
    using MyWebShop.Services.Cartridges;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public class CartridgesSearchQueryModel
    {
        public const int CartridgesPerPage = 3;
        public string PrinterBrand { get; init; }
        public IEnumerable<CartridgePrinterServiceModel> PrintersBrands { get; set; }
        public IEnumerable<string> Models{ get; set; }
        [Display(Name ="Search by text")]
        public string SearchTerm { get; init; }
        public int CurrentPage { get; init; } = 1;
        public int TotalCartridges { get; set; }
        public CartridgesSorting Sorting { get; init; }
        public IEnumerable<CartridgeServiceModel> Cartridges { get; set; }
    }
}

MyWebShop/Models/Cartridges/CartridgesSorting.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyWebShop.Models.Cartridges
{
    public enum CartridgesSorting
    {
        DateCreated = 0,
        PrinterBrandAndModel=1
    }
}

MyWebShop/Controllers/CartridgesController.cs
namespace MyWebShop.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using MyWebShop.Models.Cartridges;
    using MyWebShop.Services.Cartridges;
    using MyWebShop.Infrastructure;


    public class CartridgesController : Controller
    {
       // private readonly ApplicationDbContext data;
        private readonly ICartridgeService cartridges;

        public CartridgesController(ICartridgeService cartridges)
            => this.cartridges = cartridges;


        public IActionResult Add() => View(new CartridgeFormModel
        {
            Colours = this.cartridges.AllColours(),
            Printers=this.cartridges.AllPrinterBrands()
        });
        



        [HttpPost]
        public IActionResult Add(CartridgeFormModel cartridge)
        {
            if (!this.cartridges.ColourExists(cartridge.ColourId))
            {
                this.ModelState.AddModelError(nameof(cartridge.ColourId), "Colour does not exist.");
            }
            if (!this.cartridges.PrinterBrandExists(cartridge.PrinterId))
            {
                this.ModelState.AddModelError(nameof(cartridge.PrinterId), "Printer Brand does not exist.");
            }

            if (!ModelState.IsValid)
            {
                cartridge.Colours = this.cartridges.AllColours();
                cartridge.Printers = this.cartridges.AllPrinterBrands();

                return View(cartridge);
            }

            this.cartridges.Create(
                cartridge.Model,
                cartridge.Description,
                cartridge.ImageUrl,
                cartridge.Price,
                cartridge.ColourId,
                cartridge.PrinterId);

            return RedirectToAction(nameof(All));

        }


        public IActionResult All([FromQuery]CartridgesSearchQueryModel query)
        {
            var queryResult = this.cartridges.All(
                query.PrinterBrand,
                query.SearchTerm,
                query.Sorting,
                query.CurrentPage,
                CartridgesSearchQueryModel.CartridgesPerPage);

            var printerBrands = this.cartridges.AllPrinterBrands();

            query.PrintersBrands = printerBrands;
            query.TotalCartridges = queryResult.TotalCartridges;
            query.Cartridges = queryResult.Cartridges;


            return View(query);

        }

        [Authorize]
        public IActionResult Edit(int id)
        {
            var userId = this.User.Id();

            if (!User.IsAdmin())
            {
                return Unauthorized();
            }

            var cartridge = this.cartridges.Details(id);


            return View(new CartridgeFormModel
            {
                
                Model = cartridge.Model,
                Description = cartridge.Description,
                ImageUrl = cartridge.ImageUrl,
                Price = cartridge.Price,
                ColourId = cartridge.ColourId,
                Colours = this.cartridges.AllColours(),
                PrinterId=cartridge.PrinterId,
                Printers=this.cartridges.AllPrinterBrands()
            });
        }

        [HttpPost]
        [Authorize]
        public IActionResult Edit(int id, CartridgeFormModel cartridge)
        {
            

            if (!User.IsAdmin())
            {
                return Unauthorized();
            }

            if (!this.cartridges.ColourExists(cartridge.ColourId))
            {
                this.ModelState.AddModelError(nameof(cartridge.ColourId), "Colour does not exist.");
            }

            if (!this.cartridges.PrinterBrandExists(cartridge.PrinterId))
            {
                this.ModelState.AddModelError(nameof(cartridge.PrinterId), "Printer Brand does not exist.");
            }
            if (!ModelState.IsValid)
            {
                cartridge.Colours = this.cartridges.AllColours();
                cartridge.Printers = this.cartridges.AllPrinterBrands();

                return View(cartridges);
            }

            if (!User.IsAdmin())
            {
                return BadRequest();
            }

            this.cartridges.Edit(
                id,
                cartridge.Model,
                cartridge.Description,
                cartridge.ImageUrl,
                cartridge.Price,
                cartridge.ColourId,
                cartridge.PrinterId);

            return RedirectToAction(nameof(All));
        }


    }
}

MyWebShop/Views/Cartridges/Add.cshtml
@model CartridgeFormModel

@{
    ViewBag.Title = "Add Cartridge";
}

<partial name="_CartridgeFormPartial" model="@Model" />

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

MyWebShop/Views/Cartridges/All.cshtml
@model CartridgesSearchQueryModel

@{ ViewData["Title"] = "All Cartridges"; }

<form method="get">
    <div class="row">
        <div class="col-md-3">
            <div class="form-group">
                <div class="form-group">
                    <label asp-for="PrinterBrand"></label>
                    <select asp-for="PrinterBrand" class="form-control">
                        <option value="">All</option>

                        @foreach (var brand in Model.PrintersBrands)
                        {
                            <option value="@brand">@brand</option>
                        }
                    </select>
                </div>
            </div>
        </div>

        <div class="col-md-3">
            <div class="form-group">
                <label asp-for="SearchTerm"></label>
                <input asp-for="SearchTerm" class="form-control" placeholder="Search...">
            </div>
        </div>

        <div class="col-md-3">
            <div class="form-group">
                <div class="form-group">
                    <label asp-for="Sorting"></label>
                    <select asp-for="Sorting" class="form-control">
                        <option value="0">Date Created</option>
                        <option value="1">PrinterBrand And Model</option>
                    </select>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <input type="submit" class="btn btn-primary" value="Search">
            </div>
        </div>
    </div>
</form>



@{ var previousPage = Model.CurrentPage - 1;
                if (previousPage < 1)
                {
                    previousPage = 1;
                }

                var maxPage = Math.Ceiling((double)Model.TotalCartridges / CartridgesSearchQueryModel.CartridgesPerPage); }

<div class="row text-center">
    <div class="col-md-6">
        <a class="btn btn-primary @(Model.CurrentPage==1 ?"disabled":string.Empty)"
           asp-controller="Cartridges"
           asp-action="All"
           asp-route-currentPage="@previousPage"
           asp-route-printerBrand="@Model.PrinterBrand"
           asp-route-searchTerm="@Model.SearchTerm"
           asp-route-Sorting="@((int)Model.Sorting)">Previous Page</a>
    </div>
    <div class="col-md-6">
        <a class="btn btn-primary @(Model.CurrentPage==maxPage ?"disabled":string.Empty)"
           asp-controller="Cartridges"
           asp-action="All"
           asp-route-currentPage="@(Model.CurrentPage+1)"
           asp-route-printerBrand="@Model.PrinterBrand"
           asp-route-searchTerm="@Model.SearchTerm"
           asp-route-Sorting="@((int)Model.Sorting)">Next Page</a>
    </div>
</div>

@if (!Model.Cartridges.Any())
{
    <h2 class="text-center">No cars found by the given criteria!</h2>
}

<partial name="_CartridgePartial" model="@Model.Cartridges" />

MyWebShop/Views/Cartridges/_CartridgeFormPartial.cshtml
@model CartridgeFormModel

<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <h2 class="heading-margin text-center">@ViewBag.Title</h2>

        <form method="post">
            <div class="form-group">
                <label asp-for="Model"></label>
                <input asp-for="Model" class="form-control" placeholder="Type Model here">
                <span asp-validation-for="Model" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description"></label>
                <textarea asp-for="Description" rows="4" class="form-control" placeholder="Type information abaut this model"></textarea>
                <span asp-validation-for="Description" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl"></label>
                <input asp-for="ImageUrl" class="form-control" placeholder="Type URL here...">
                <span asp-validation-for="ImageUrl" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price"></label>
                <input asp-for="Price" class="form-control" placeholder="Type Price here...">
                <span asp-validation-for="Price" class="small text-danger"></span>
            </div>
            <div class=" form-group">
                <label asp-for="ColourId"></label>
                <select asp-for="ColourId" class="form-control">
                    @foreach (var colour in Model.Colours)
                    {
                        <option value="@colour.Id">@colour.Name</option>
                    }
                </select>
                <span asp-validation-for="ColourId" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PrinterId"></label>
                <select asp-for="PrinterId" class="form-control">
                    @foreach (var printer in Model.Printers)
                    {
                        <option value="@printer.Id">@printer.Brand</option>
                    }
                </select>
                <span asp-validation-for="PrinterId" class="small text-danger"></span>
            </div>
            <input class="btn btn-primary" type="submit" value="Save" />
        </form>
    </div>
</div>

MyWebShop/Views/Cartridges/_CartridgePartial.cshtml
@model IEnumerable<CartridgeServiceModel>

<div class="row">
    @foreach (var cartridge in Model)
    {
        <div class="col-md-4">
            <div class="card mb-3">
                <img class="card-img-top" src="@cartridge.Price $" alt="@cartridge.PrinterBrand @cartridge.Model">
                <div class="card-body text-center">
                    <h5 class="card-title text-center">@cartridge.Price $ @cartridge.PrinterBrand @cartridge.Model (@cartridge.ColourName)</h5>
                    <a asp-controller="Cartridges" asp-action="Details" asp-route-id="@cartridge.Id" class="btn btn-primary">View</a>

                    @if (User.IsInRole(WebConstants.AdministratorRoleName))
                    {
                        <a asp-controller="Cartridges" asp-action="Edit" asp-route-id="@cartridge.Id" class="btn btn-warning">Edit</a>
                        <a asp-controller="Cartridges" asp-action="Delete" asp-route-id="@cartridge.Id" class="btn btn-danger">Delete</a>
                    }


                </div>
            </div>
        </div>
    }
</div>